In [3]:
import numpy as np
a=np.random.randiant(0,20,15)
a

AttributeError: module 'numpy.random' has no attribute 'randiant'

In [4]:
a=np.arange(5)
np.sin(a)


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [5]:
np.cos(a)


array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [5]:
import numpy as np
x=np.array([1,2,3,1])
y=np.array(([1,2,3],[5,6,1]))
x.mean()

np.float64(1.75)

In [4]:
np.median(x)

np.float64(1.5)

In [6]:
np.median(y,axis=-1)

array([2., 5.])

In [7]:
x.std()

np.float64(0.82915619758885)

In [8]:
data=np.loadtxt('populations.txt')

In [9]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [10]:
year,hares,lynxes,carrots=data.T
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [11]:
population=data[:,1:]
population

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [ ]:
population.std(axis=0)


array([20897.90645809, 16254.59153691,  3322.50622558])

In [13]:
population.std(axis=1)

array([18176.23601177, 19614.67704439, 24668.33327703, 19225.21492439,
       10030.73055941,  9530.41913501,  9458.79954798, 12319.18106946,
       14923.434219  , 13472.52347888, 15759.51211879, 16967.22330456,
       18751.53327064, 23553.39088586,  5266.87763291, 13018.02169644,
       10757.4263754 , 14578.82787546, 14819.88154099, 13501.68713737,
       15873.31793363])

In [3]:
import numpy as np
a=np.tile(np.arange(0,40,10),(3,1))
print(a)
print("*************")
a=a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
*************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [4]:
b=np.array([1,2,3])
a+b


array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [5]:
a=np.arange(0,40,10)
a.shape

(4,)

In [6]:
a=a[:,np.newaxis]
a.shape

(4, 1)

In [7]:
a+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [9]:
a=np.array(([1,2,3],[4,5,6]))
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [10]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [12]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [13]:
b=a.ravel()
print(b)

[1 2 3 4 5 6]


In [14]:
b=b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
print(b.shape)

(2, 3)


In [16]:
b[0,0]=100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [18]:
a=np.zeros((3,2))
b=a.T.reshape(3*2)
b[0]=50
a
b

array([50.,  0.,  0.,  0.,  0.,  0.])

In [19]:
z=np.array([1,2,3])
z[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [20]:
a=np.arange(4*3*2)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
a=np.arange(4*3*2).reshape(4,3,2)
a
a.shape

(4, 3, 2)

In [22]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [24]:
a[0,2,1]

np.int64(5)

In [25]:
b=a
a.reshape((4,))

ValueError: cannot reshape array of size 24 into shape (4,)

In [27]:
a=np.array(([5,4,6],[2,3,2]))
b=np.sort(a,axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [29]:
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [30]:
a=np.array([4,3,1,2])
j=np.argsort(a)
j

array([2, 3, 1, 0])

In [31]:
a[j]

array([1, 2, 3, 4])

In [2]:
import numpy as np
import pandas as pd
df=pd.read_csv("Student.txt.csv")

In [3]:
df

student_id  math_original  science_original  english_original  attendance  \
0         1001          82.45             76.70             65.00          71   
1         1002          72.93             68.88             65.30          90   
2         1003          84.72             64.79             65.61          99   
3         1004          97.85             73.50             65.91          70   
4         1005          71.49             97.72             66.21          97   
..         ...            ...               ...               ...         ...   
95        1096          53.05             69.76             93.79          92   
96        1097          79.44             98.92             94.09          91   
97        1098          78.92             75.72             94.39          88   
98        1099          75.08             95.68             94.70          94   
99        1100          71.48             85.25             95.00          95   

    math_int8  attendance_float32  weighted_total  math_mean  science_mean  \
0          82                  71           76.08    73.4422       79.4485   
1          72                  90           69.60    73.4422       79.4485   
2          84                  99           72.97    73.4422       79.4485   
3          97                  70           81.34    73.4422       79.4485   
4          71                  97           79.35    73.4422       79.4485   
..        ...                 ...             ...        ...           ...   
95         53                  92           69.08    73.4422       79.4485   
96         79                  91           89.92    73.4422       79.4485   
97         78                  88           81.67    73.4422       79.4485   
98         75                  94           87.20    73.4422       79.4485   
99         71                  95           82.18    73.4422       79.4485   

    ...  grade  bonus_points  final_score  math_original_zscore  \
0   ...      C             0        76.08                 0.661   
1   ...      D             0        69.60                -0.038   
2   ...      C             0        72.97                 0.828   
3   ...      B             0        81.34                 1.792   
4   ...      C             0        79.35                -0.143   
..  ...    ...           ...          ...                   ...   
95  ...      D             0        69.08                -1.497   
96  ...      B             5        94.92                 0.440   
97  ...      B             0        81.67                 0.402   
98  ...      B             5        92.20                 0.120   
99  ...      B             0        82.18                -0.144   

    science_original_zscore  english_original_zscore  \
0                    -0.238                   -1.706   
1                    -0.917                   -1.672   
2                    -1.272                   -1.637   
3                    -0.516                   -1.603   
4                     1.585                   -1.569   
..                      ...                      ...   
95                   -0.841                    1.569   
96                    1.689                    1.603   
97                   -0.323                    1.637   
98                    1.408                    1.672   
99                    0.503                    1.706   

    math_original_percentile  science_original_percentile  \
0                      35.70                        60.20   
1                      45.19                        60.37   
2                      45.60                        60.66   
3                      46.30                        61.48   
4                      48.55                        61.63   
..                       ...                          ...   
95                     97.85                        97.72   
96                     98.07                        98.50   
97                     98.47                        98.87   
98    

In [4]:
df=pd.read_csv("nyc_weather.csv")
df

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   
16  1/17/2016           36        23        66                 29.78   
17  1/18/2016           25         6        53                 29.83   
18  1/19/2016           22         3        42                 30.03   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
21  1/22/2016           26         6        41                 30.21   
22  1/23/2016           26        21        78                 29.77   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
25  1/26/2016           43        29        56                 30.03   
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5       NaN   
1                10           7.0               0           3       NaN   
2                10           8.0               0           1       NaN   
3                10           9.0               0           3       NaN   
4                10           5.0               0           0       NaN   
5                10           4.0               0           0       NaN   
6                10           2.0               0           3       NaN   
7                10           4.0               0           8       NaN   
8                 9           8.0               T           8      Rain   
9                 4           NaN             1.8           7      Rain   
10               10           NaN               0           1       NaN   
11               10           6.0               T           4       NaN   
12               10          10.0               0           0       NaN   
13               10           5.0               T           7       NaN   
14                9           5.0               T           2       NaN   
15                8           7.0            0.24           7      Rain   
16                8           6.0            0.05           6  Fog-Snow   
17                9          12.0               T           2      Snow   
18               10          11.0               0           1       NaN   
19               10           6.0               0           2       NaN   
20               10           6.0               0           1       NaN   
21                9           NaN            0.01      

In [5]:
df['Temperature'].max()

50

In [6]:
df['EST'][df['Events']=='Rain']

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

In [7]:
df["WindSpeedMPH"].mean()

np.float64(6.892857142857143)