In [3]:
import numpy as np
a=np.random.randiant(0,20,15)
a

AttributeError: module 'numpy.random' has no attribute 'randiant'

In [4]:
a=np.arange(5)
np.sin(a)


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [5]:
np.cos(a)


array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [5]:
import numpy as np
x=np.array([1,2,3,1])
y=np.array(([1,2,3],[5,6,1]))
x.mean()

np.float64(1.75)

In [4]:
np.median(x)

np.float64(1.5)

In [6]:
np.median(y,axis=-1)

array([2., 5.])

In [7]:
x.std()

np.float64(0.82915619758885)

In [8]:
data=np.loadtxt('populations.txt')

In [9]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [10]:
year,hares,lynxes,carrots=data.T
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [11]:
population=data[:,1:]
population

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [12]:
population.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])